In [1]:
import pandas as pd
df = pd.read_csv('data/netflix_titles.csv', sep='|')

In [3]:
df.set_index('show_id', inplace=True)

In [7]:
df.loc['s2202', 'director'] = 'Greg Whiteley'

In [9]:
df.loc['s2202', 'director']

'Greg Whiteley'

In [13]:
df.loc[['s2881', 's3601'], 'duration'] = 'Gone Too Soon'

In [14]:
df.loc[['s2881', 's3601']]

,Unnamed: 0,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,,
s2881,2880,TV Show,I Am Not Okay With This,NaN,"Sophia Lillis, Wyatt Oleff, Kathleen Rose Perk...",United States,"February 26, 2020",2020,TV-MA,Gone Too Soon,"TV Comedies, TV Dramas, TV Sci-Fi & Fantasy","Angsty Syd navigates high school awkwardness, ..."
s3601,3600,TV Show,GLOW,NaN,"Alison Brie, Betty Gilpin, Marc Maron, Britney...",United States,"August 9, 2019",2019,TV-MA,Gone Too Soon,"TV Comedies, TV Dramas","In 1980s LA, a crew of misfits reinvent themse..."

In [16]:
df.rename(columns={'release_year':'release_yr'})
#df.rename({'release_year':'release_yr'}, axis=1)

,Unnamed: 0,type,title,director,cast,country,date_added,release_yr,rating,duration,listed_in,description
show_id,,,,,,,,,,,,
s1,0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
s8803,8802,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
s8804,8803,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
s8805,8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
s8806,8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
s8807,8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [17]:
df['rating'].replace(['NR', 'UR'], 'No Rating').value_counts()

TV-MA        3207
TV-14        2160
TV-PG         863
R             799
PG-13         490
TV-Y7         334
TV-Y          307
PG            287
TV-G          220
No Rating      83
G              41
TV-Y7-FV        6
NC-17           3
74 min          1
84 min          1
66 min          1
Name: rating, dtype: int64

In [20]:
df['is_fav'] = 'False'

In [25]:
favs = ['Young Royals', 'Dark', 'Big Mouth']
df.loc[df['title'].isin(favs), 'is_fav'] = True

In [27]:
df['is_fav'].value_counts()

False    8804
True        3
Name: is_fav, dtype: int64

In [30]:
df.describe(include='all')

,Unnamed: 0,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,is_fav
count,8807.000000,8807,8807,6174,7982,7976,8797,8807.000000,8803,8804,8807,8807,8807
unique,NaN,2,8807,4528,7692,748,1767,NaN,17,221,514,8775,2
top,NaN,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope...",False
freq,NaN,6131,1,19,19,2818,109,NaN,3207,1792,362,4,8804
mean,4403.000000,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN,NaN
std,2542.506244,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN,NaN
25%,2201.500000,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN,NaN
50%,4403.000000,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN
75%,6604.500000,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN
max,8806.000000,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN,NaN